### ISSUE TITLE
Bluetooth control

### ISSUE THREAD

**Issue by pu3lkah** [schoolpost/CinePI#3]
Hi, I can't manage to connect the raspberry pi to my android device via bluetooth, is there anything I should configure on the board first ?

**Comment by schoolpost** [comment]
What application are you trying to connect it with? You need to use an app that is designed for Blackmagic Cameras.

**Comment by pu3lkah** [comment]
I'm using the control black magic camera app for android. Tom antos showcased it in one of his videos by using it with a bmpcc4k and it works flawlessly, but on my phone, as you can see I can only find one device (I'll add a screenshot) and I'm unable to pair to it, even after clearing the bluetooth and the app cache, restarting my phone and/or the pi, etc...![Screenshot_2021-03-20-08-39-46-959_com.sayeffect.cameracontrol.blackmagic.bmpcc4.jpg](https://user-images.githubusercontent.com/43523295/111862810-ff1a3600-8957-11eb-851f-692ccc95f684.jpg)
[Edit, I also try formatting the sd card and reinstalling cinepi on it but the results are the same]

**Comment by schoolpost** [comment]
> I'm using the control black magic camera app for android. Tom antos showcased it in one of his videos by using it with a bmpcc4k and it works flawlessly, but on my phone, as you can see I can only find one device (I'll add a screenshot) and I'm unable to pair to it, even after clearing the bluetooth and the app cache, restarting my phone and/or the pi, etc...!
> [Edit, I also try formatting the sd card and reinstalling cinepi on it but the results are the same]

The Bluetooth service starts up when booted so nothing you have to do on the user side. 

This will be something to look into, I was under the assumption most of these applications would connect with a similar procedure, but seems not to be the case. I do not have any android device to test with at the moment, so you may have to experiment /tinker with it yourself for the time being. 

If you want to look at the source go to the controls-thread folder in the home directory of the installation.

**Comment by pu3lkah** [comment]
Okay, thanks a lot, i'll try getting my hands on an ios device to test it out. Do you think there might be a way to control the settings with a wired controller ? Either mouse and keyboard or small arduino controller ?

**Comment by nocantsin** [comment]
The Android app _My Camera Controller_ (gratis w/ ads) works with the CinePi:
https://play.google.com/store/apps/details?id=com.taskdesigns786.android.mycameracontroller&hl=en_US&gl=US

**Comment by Leoba2700** [comment]
hi i have the same issue but with the bluetooth+ for Blackmagic app on my iPhoneX. I Cant find any raspberry bluetooth connection even in my bluetooth option. my raspberry pi 4 is brand new, there is nothing to activate in order to make it work ?

**Comment by schoolpost** [comment]
> hi i have the same issue but with the bluetooth+ for Blackmagic app on my iPhoneX. I Cant find any raspberry bluetooth connection even in my bluetooth option. my raspberry pi 4 is brand new, there is nothing to activate in order to make it work ?

The Bluetooth service auto starts when the Pi is booted. I also use a iPhoneXR with Bluetooth+ and have not had the same issue you are having. Go to the Bluetooth settings of your iPhone and if you see your raspberry pi already paired, you should try to "forget device" maybe that will help.

**Comment by Leoba2700** [comment]
that's weird... the thing is that the raspberry pi doesn't even show up in my bluetooth settings

**Comment by nocantsin** [comment]
I am having the same issues - both the Android and the recommended iOS app.

**Comment by schoolpost** [comment]
Will need to investigate this, may have been a change that happened on the IOS Application side that breaks compatibility.

**Comment by Leoba2700** [comment]
is it possible to change the settings without the apps ? if yes, what is the way to do it ?

**Comment by schoolpost** [comment]
> is it possible to change the settings without the apps ? if yes, what is the way to do it ?

Yes, you could create your own scripts that will control camera settings, but you will need to decide to use bluetooth, wifi or physicals controls to obviously interact with the Pi. 

You need to look into v4l2-ctl 

It's a command line utlity that allows you to control the settings of a v4l2 device ( /dev/video0 ) in this case. It's a bit more low level, you wont be changing "shutter speed" or "frame rate" but if you read up on what each does you should get an idea.

**Comment by Leoba2700** [comment]
unfornatly I don't think I have the capacity to create my own script maybe ill try with an other app

**Comment by schoolpost** [comment]
> unfornatly I don't think I have the capacity to create my own script maybe ill try with an other app

I have a development version that is newer than what is posted here on github, that one works just fine with Bluetooth+ app. I don't have time right now to upload it,  but I will try to do that soon. 

Otherwise, yes your best luck would be to see if some other apps might work.

**Comment by schoolpost** [comment]
Should be addressed in the latest 1.0.1 release. Please test and report back.

**Comment by tallmansixfour** [comment]
Hey schoolpost,

having trouble connecting with any app on android. tried Control Blackmagic Camera (lost $12 - no returns), Blackmagic BlueConnect (goodbye $12), Blackmagic Camera control (free). tried clearing storage and cache on individual apps. nope. is there another cache to clean somewhere? 

installed 1.0.1 Still shows v.1.0.0 Is something wrong here? 
used 20210920_022913_pi_clone.img

I understand it's alpha, but could you test with one known-good Android app please?

thanks

Chris in Montreal

**Comment by schoolpost** [comment]
> Hey schoolpost,
> 
> having trouble connecting with any app on android. tried Control Blackmagic Camera (lost $12 - no returns), Blackmagic BlueConnect (goodbye $12), Blackmagic Camera control (free). tried clearing storage and cache on individual apps. nope. is there another cache to clean somewhere?
> 
> installed 1.0.1 Still shows v.1.0.0 Is something wrong here? used 20210920_022913_pi_clone.img
> 
> I understand it's alpha, but could you test with one known-good Android app please?
> 
> thanks
> 
> Chris in Montreal

Hi Chris, 

Unfortunately I do not have any android devices to test with. Can you test with an iOS device? 
This will help narrow down if it's a device specific problem or something else. 

I also don't particularly like that a project like this would enforce a paid product, I was under the impression more free options would be available, which it seems is not the case. 

I will look into developing something more general purpose for camera control. But I do not have any timeline on this.

**Comment by tallmansixfour** [comment]
thanks for the reply. i did try the free options first, but noting. My Camera Controller shows a device (code) then shows connecting and even initializing, but then nothing. paid options usually offer a refund for 5-10 minutes, but i the case of the two i mentioned, no such option was presented. im eager to get my project working with your system, raspivid pales in comparison. do you have a Patreon?

**Comment by nils1976** [comment]
Hi guys,

First of all really cool project....
Managed to make that work in less than an hour? But also have the BT error.
My "camera" is also complaining, that it is v 1.0.0 

I can connect to the pi via ssh. But was not able to find where the defaults are set. Therefore it is not usable at the moment.

How can I provide help to make the BT stuff work? Tried different apps und different platforms....(android and IOs) 
but with no luck. Is there kind of an log? Didn't find that in /var/log....
where is the patreon link? or Paypal...? Think you need beer or coffe support!!

Also i doesn't work with the DSI-connected Display from raspberry...not a big thing, but maybe someone like to know.
It there a restriction in resolution?

But what I can say: Using a passive CSI to HDMI (not converting to HDMI!!!!!) adapter works fine with a 2m cable.
Which makes it also more intersting for independent filming, as you can put the "recorder" away from the head.
Like our plan is: putting the camera on a handlebar of a bike....having the recoder in the back or bag....;-)

kind regards Nils

**Comment by schoolpost** [comment]
> Hi guys,
> 
> First of all really cool project.... Managed to make that work in less than an hour? But also have the BT error. My "camera" is also complaining, that it is v 1.0.0
> 
> I can connect to the pi via ssh. But was not able to find where the defaults are set. Therefore it is not usable at the moment.
> 
> How can I provide help to make the BT stuff work? Tried different apps und different platforms....(android and IOs) but with no luck. Is there kind of an log? Didn't find that in /var/log.... where is the patreon link? or Paypal...? Think you need beer or coffe support!!
> 
> Also i doesn't work with the DSI-connected Display from raspberry...not a big thing, but maybe someone like to know. It there a restriction in resolution?
> 
> But what I can say: Using a passive CSI to HDMI (not converting to HDMI!!!!!) adapter works fine with a 2m cable. Which makes it also more intersting for independent filming, as you can put the "recorder" away from the head. Like our plan is: putting the camera on a handlebar of a bike....having the recoder in the back or bag....;-)
> 
> kind regards Nils

Very kind of you Nils, glad you can find a use case for this project. 
You can donate to my paypal here: 
[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZDU59MDJ3VXF6&source=url)

As far a bluetooth control is concerned, It seems to me that only application that works right now is a paid app called "Bluetooth+" that is available on IOS. This is the app I did all my testing/development with. I did not realize that although I was reverse engineering a standard protocol, some applications do not seem to detect it. 

The way you control the camera's settings is mostly through v4l2-ctl. You can ssh into the pi and list the available controls and mess around with them to see how it changes the image. But also I'm looking into a better way to do this. 

I was recently looking to attach a display to the camera, over DPI using the GPIO pins; but even this proved to be a problem and it seems like the reason for this has to do with the i2c being used by the camera module and therefore it claims the i2c so no other peripheral that uses i2c can be used. ( simplification ) 

Would love to see some footage you film when you are done with your setup. 

Csaba Nagy

**Comment by tallmansixfour** [comment]
Thanks for the update. Made a donation - hope it helps. There is great
potential here. I want to use the setup for stereoscopic fiming.
Chris

**Comment by nils1976** [comment]
Ok now it is getting weird.....I was asking for a link to donate....some else donates....but I also....
I was using the bluetooth+ app at first time.....doesn't work....
Yes I can confirm, that it boots with DSI connected, can also see the overlay from the mmal stuff, than it runs into normal boot login, I think at the point where the sensor get initialized....anyhow....not a big thing, ordered a 7" Display yesterday.
If you are interested in getting i2c data, I have a little USB-analyzer...
So I will try the app again...it is always complaining the I should remove the camera from the bluetooth settings (can even put it in there, because it is not showing up in the OS....but in the app)

![IMG_9349](https://user-images.githubusercontent.com/7984103/150922326-60760d9e-e545-45d8-a4fa-3bdca208c4ea.PNG)
.

Let me know if I can do something from my side. Logs/debug output etc....

Btw: If I don't want to use XFS, what is the next best choice? Ntfs? or HFS?

If we can manage to get that work, you will get footage. Our apprentice will generate some....

**Comment by nils1976** [comment]
Hey there,
is there a simple way to start the camera, lets say 2k 25p? I see that i can set the vertical blanking...but not shure if I exactly hit the 25p:  v4l2-ctl -d /dev/video0  --set-ctrl vertical_blanking=1500 gives me a 25p, not shure if this is on the point.......but I think it also depending on the resolution....I am not that python guy/programming guy, so a feedback would be nice..
I understood that your scripts reads the settings that are actual....an it is fine for me to set that manual, without using the app


Regards Nils

**Comment by schoolpost** [comment]
> Hey there, is there a simple way to start the camera, lets say 2k 25p? I see that i can set the vertical blanking...but not shure if I exactly hit the 25p: v4l2-ctl -d /dev/video0 --set-ctrl vertical_blanking=1500 gives me a 25p, not shure if this is on the point.......but I think it also depending on the resolution....I am not that python guy/programming guy, so a feedback would be nice.. I understood that your scripts reads the settings that are actual....an it is fine for me to set that manual, without using the app
> 
> Regards Nils

Hi Nils,

Yes, I also would need to review the code to confirm this, but I do believe it is the VBLANK that needs to be adjusted for this. 

There is some more information about this here when I was also investigating how it works: https://forums.raspberrypi.com/viewtopic.php?p=1789990#p1789990

Regards,

Csaba Nagy
